server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_practica
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Crud practice"
appVersion: "1.0.0"
